### ISSUE TITLE
dunstify does not build with libnotify >=0.8.4

### ISSUE THREAD

**Issue by ajacoutot** [dunst-project/dunst#1442]
Hi.

Since libnotify 0.8.4, the priv pointer in NotifyNotification is not exposed externally anymore.
See https://gitlab.gnome.org/GNOME/libnotify/-/commit/f413d8109cd2203dee08da3ec116bf8adc81e6ca

```
dunstify.c:205:23: error: no member named 'priv' in 'struct _NotifyNotification'
    knickers *kn = n->priv;
                   ~  ^
dunstify.c:213:23: error: no member named 'priv' in 'struct _NotifyNotification'
    knickers *kn = n->priv;
                   ~  ^
```

**Comment by bynect** [comment]
fixed by #1444
